version: 0.0
os: linux

files:
  - source: /
    destination: /opt/testapp # 인스턴스에서 파일이 저장될 위치

permissions:
  - object: /opt/testapp/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root